version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5433:5432
    volumes:
      - ./database/SQL/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - 8080:80

  contact_form:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./dist:/usr/dist/app/dist
